coverage:
  precision: 2
  round: down
  range: "75...95"

  status:
    project:
      default:
        target: "80%"
    patch:
      default:
        target: "80%"
    changes:
      default: off

comment:
  layout: "header, reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes
