---
apiVersion: v1
kind: Template
metadata:
  name: cloudigrade-smoke
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: smoke-iqe-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        imagePullSecrets:
          - name: quay-cloudservices-pull
        containers:
          - image: 'quay.io/cloudservices/iqe-tests:cloudmeter'
            imagePullPolicy: Always
            name: cloudigrade-smoke-iqe
            command:
              - iqe_runner.sh
            env:
              - name: ENV_FOR_DYNACONF
                value: stage_proxy
              - name: IQE_PLUGINS
                value: cloudmeter
              - name: IQE_MARKER_EXPRESSION
                value: smoke

parameters:
- name: IMAGE_TAG
  value: ''
  required: true
