---
apiVersion: v1
kind: Template
metadata:
  name: cloudigrade-smoke
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: smoke-iqe-${IMAGE_TAG}
  spec:
    backoffLimit: 5
    template:
      spec:
        restartPolicy: Never
        imagePullSecrets:
          - name: quay-cloudservices-pull
        containers:
          - image: 'quay.io/cloudservices/iqe-tests:cloudmeter'
            imagePullPolicy: Always
            name: cloudigrade-smoke-iqe
            command:
              - iqe_runner.sh
            env:
              - name: ENV_FOR_DYNACONF
                value: stage_proxy
              - name: IQE_PLUGINS
                value: cloudmeter
              - name: IQE_MARKER_EXPRESSION
                value: smoke
              - name: DYNACONF_IQE_VAULT_LOADER_ENABLED
                value: "true"
              - name: DYNACONF_IQE_VAULT_VERIFY
                value: "true"
              - name: DYNACONF_IQE_VAULT_URL
                valueFrom:
                  secretKeyRef:
                    key: url
                    name: iqe-vault
                    optional: true
              - name: DYNACONF_IQE_VAULT_MOUNT_POINT
                valueFrom:
                  secretKeyRef:
                    key: mountPoint
                    name: iqe-vault
                    optional: true
              - name: DYNACONF_IQE_VAULT_ROLE_ID
                valueFrom:
                  secretKeyRef:
                    key: roleId
                    name: iqe-vault
                    optional: true
              - name: DYNACONF_IQE_VAULT_SECRET_ID
                valueFrom:
                  secretKeyRef:
                    key: secretId
                    name: iqe-vault
                    optional: true
              - name: DYNACONF_IQE_VAULT_GITHUB_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: githubToken
                    name: iqe-vault
                    optional: true

parameters:
- name: IMAGE_TAG
  value: ''
  required: true
