---
apiVersion: v1
kind: Template
metadata:
  name: cloudigrade-smoke
objects:
- apiVersion: batch/v1
  kind: ClowdJobInvocation
  metadata:
    name: smoke-iqe-${IMAGE_TAG}
  spec:
    appName: cloudigrade
    testing:
      iqe:
        debug: false
        dynaconfEnvName: clowder_smoke
        filter: ''
        marker: 'smoke'
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
