---
apiVersion: v1
kind: Template
metadata:
  name: cloudigrade-smoke
objects:
- apiVersion: cloud.redhat.com/v1alpha1
  kind: ClowdJobInvocation
  metadata:
    name: cloudigrade-smoke-${IMAGE_TAG}
  spec:
    appName: cloudigrade
    testing:
      iqe:
        debug: false
        dynaconfEnvName: clowder_smoke
        filter: ''
        marker: 'smoke'
parameters:
- name: IMAGE_TAG
  value: ''
  required: true
