---
# Destroy Block
- block:
  - name: destroy / ec2 auto scaling group
    ec2_asg:
      name: "{{ec2_asg_name}}"
      state: absent

  - name: destroy / ec2 launch configuration
    ec2_lc:
      name: "{{ec2_lc_name}}"
      state: absent

  - name: destroy / ecs cluster
    ecs_cluster:
      name: "{{ecs_cluster_name}}"
      state: absent

  - name: query / ecs iam role
    iam_role_info:
      name: "{{ecs_iam_role_name}}"
    register: iam_role

  - name: destroy / ecs iam inline policies
    iam_policy:
      iam_type: role
      iam_name: "{{ecs_iam_role_name}}"
      policy_name: "{{ item }}"
      skip_duplicates: false
      state: absent
    loop: "{{ iam_role.iam_roles[0].inline_policies | default([]) }}"

  - name: destroy / ecs iam role
    iam_role:
      name: "{{ecs_iam_role_name}}"
      delete_instance_profile: true
      purge_policies: true
      state: absent

  when: ecs_state == "absent"
