# Generated by Django 2.1.10 on 2019-07-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_awscloudaccount_aws_access_key_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='concurrentusage',
            name='_instances_list',
            field=models.TextField(blank=True, db_column='instances_list', null=True),
        ),
    ]
