# Generated by Django 2.1.10 on 2019-07-18 19:20

from django.db import migrations


def delete_concurrentusage(apps, schema_editor):
    """Delete all concurrentusage objects."""
    ConcurrentUsage = apps.get_model("api", "ConcurrentUsage")
    ConcurrentUsage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_store_instances_list"),
    ]

    operations = [migrations.RunPython(delete_concurrentusage)]
