# Generated by Django 2.1.10 on 2019-07-23 14:03

from django.db import migrations


def delete_concurrentusage(apps, schema_editor):
    """Delete all concurrentusage objects (again)."""
    ConcurrentUsage = apps.get_model("api", "ConcurrentUsage")
    ConcurrentUsage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_delete_concurrentusage"),
    ]

    operations = [migrations.RunPython(delete_concurrentusage)]
