# Generated by Django 3.0.2 on 2020-01-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_concurrentusage_potentially_related_runs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machineimage",
            name="openshift_challenged",
        ),
        migrations.RemoveField(
            model_name="machineimage",
            name="rhel_challenged",
        ),
    ]
