# Generated by Django 3.0.2 on 2020-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20200122_1644"),
    ]

    operations = [
        migrations.AddField(
            model_name="machineimage",
            name="rhel_detected_by_tag",
            field=models.BooleanField(default=False),
        ),
    ]
