# Generated by Django 3.0.2 on 2020-02-19 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_machineimage_rhel_detected_by_tag"),
    ]

    operations = [
        migrations.RemoveField(model_name="awscloudaccount", name="aws_access_key_id",),
        migrations.AddField(
            model_name="cloudaccount",
            name="platform_authentication_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="platform_endpoint_id",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="platform_source_id",
            field=models.IntegerField(null=True),
        ),
    ]
