# Generated by Django 3.0.4 on 2020-03-17 20:22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_cloudaccount_is_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="enabled_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
