# Generated by Django 3.0.4 on 2020-03-17 20:22
from django.db import migrations, models
from django.db.models import F


def populate_enabled_at(apps, schema_editor):
    """
    Copy all CloudAccount.created_at values to CloudAccount.enabled_at.

    At the time of this migration's definition, all existing CloudAccount instances
    just had the is_enabled field added, and we can safely assume now that they were
    enabled at time of creation.
    """
    CloudAccount = apps.get_model("api", "CloudAccount")
    CloudAccount.objects.all().update(enabled_at=F("created_at"))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_cloudaccount_enabled_at"),
    ]

    operations = [
        migrations.RunPython(populate_enabled_at),
        migrations.AlterField(
            model_name="cloudaccount",
            name="enabled_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
