# Generated by Django 3.0.4 on 2020-03-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_cloudaccount_enabled_at"),
        ("api", "0013_cloudaccount_platform_application_id"),
    ]

    operations = []
