# Generated by Django 3.0.4 on 2020-04-01 18:06

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)


def delete_cloudaccounts(apps, schema_editor):
    """Delete all CloudAccount objects with missing platform data."""
    CloudAccount = apps.get_model("api", "CloudAccount")
    filter = (
        models.Q(platform_application_id__isnull=True)
        | models.Q(platform_authentication_id__isnull=True)
        | models.Q(platform_endpoint_id__isnull=True)
        | models.Q(platform_source_id__isnull=True)
    )
    for account in CloudAccount.objects.filter(filter):
        logger.warning("Deleting CloudAccount ID %s (%s)", account.id, account)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_merge_20200323_1556"),
    ]

    operations = [
        migrations.RunPython(delete_cloudaccounts),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_application_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_authentication_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_endpoint_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_source_id",
            field=models.IntegerField(),
        ),
    ]
