# Generated by Django 3.0.4 on 2020-04-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_cloudaccount_delete_platform_null"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_application_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_authentication_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_endpoint_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="cloudaccount",
            name="platform_source_id",
            field=models.IntegerField(),
        ),
    ]
