# Generated by Django 3.0.4 on 2020-04-21 13:29
import json

import django
from django.db import migrations, models


def create_verify_tasks(apps, schema_editor):
    AwsCloudAccount = apps.get_model("api", "AwsCloudAccount")
    IntervalSchedule = apps.get_model("django_celery_beat", "IntervalSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    aws_clounts = AwsCloudAccount.objects.filter(verify_task_id__isnull=True)

    for aws_clount in aws_clounts:
        schedule, _ = IntervalSchedule.objects.get_or_create(every=1, period="days")
        verify_task = PeriodicTask.objects.create(
            interval=schedule,
            name=f"Verify {aws_clount.account_arn}.",
            start_time=aws_clount.created_at,
            task="api.clouds.aws.tasks.verify_account_permissions",
            kwargs=json.dumps(
                {
                    "account_arn": aws_clount.account_arn,
                }
            ),
        )
        aws_clount.verify_task = verify_task
        aws_clount.save()


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0011_auto_20190508_0153"),
        ("api", "0019_cloudaccount_alter_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscloudaccount",
            name="verify_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="django_celery_beat.PeriodicTask",
            ),
        ),
        migrations.RunPython(create_verify_tasks),
    ]
