# Generated by Django 3.0.4 on 2020-05-18 20:09

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def delete_orphaned_periodic_tasks(apps, schema_editor):
    """Delete verify_account_permissions PeriodicTasks that have no AwsCloudAccount."""
    AwsCloudAccount = apps.get_model("api", "AwsCloudAccount")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    tasks = PeriodicTask.objects.filter(
        task="api.clouds.aws.tasks.verify_account_permissions"
    )
    for task in tasks:
        if not AwsCloudAccount.objects.filter(verify_task=task).exists():
            logger.info(
                "%(task)s (%(kwargs)s) is not referenced by any AwsCloudAccount and "
                "will be deleted",
                {"task": task, "kwargs": task.kwargs},
            )
            task.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0011_auto_20190508_0153"),
        ("api", "0020_verify_aws_access"),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_periodic_tasks),
    ]
