# Generated by Django 3.0.4 on 2020-06-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_auto_20200605_1531"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="concurrentusage",
            name="cloud_account",
        ),
    ]
