# Generated by Django 3.0.6 on 2020-06-17 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_remove_concurrentusage_cloud_account"),
    ]

    operations = [
        migrations.DeleteModel(name="ConcurrentUsage",),
    ]
