# Generated by Django 3.0.6 on 2020-07-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_concurrentusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="concurrentusage",
            name="potentially_related_runs",
            field=models.ManyToManyField(to="api.Run"),
        ),
    ]
