# Generated by Django 3.0.9 on 2020-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_concurrentusagecalculationtask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="awscloudaccount",
            name="aws_account_id",
            field=models.DecimalField(
                db_index=True, decimal_places=0, max_digits=12, unique=True
            ),
        ),
    ]
