# Generated by Django 3.0.9 on 2020-08-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_auto_20200824_1532"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AwsEC2InstanceDefinition",
            new_name="InstanceDefinition",
        ),
    ]
