# Generated by Django 3.0.9 on 2020-08-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_auto_20200826_1418"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instancedefinition",
            options={},
        ),
        migrations.AddField(
            model_name="instancedefinition",
            name="cloud_type",
            field=models.CharField(
                choices=[
                    ("aws", "AWS EC2 instance definitions."),
                    ("azure", "Azure VM instance definitions."),
                ],
                default="aws",
                max_length=32,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instancedefinition",
            name="instance_type",
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name="instancedefinition",
            unique_together={("instance_type", "cloud_type")},
        ),
    ]
