# Generated by Django 3.0.10 on 2020-09-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0033_azurecloudaccount_azureinstance_azureinstanceevent_azuremachineimage",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cloudaccount",
            name="platform_endpoint_id",
        ),
    ]
