# Generated by Django 3.0.13 on 2021-03-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_auto_20210216_1906"),
    ]

    operations = [
        migrations.DeleteModel(
            name="instancedefinition",
        ),
    ]
