# Generated by Django 3.1.7 on 2021-04-12 17:46
from django.db import migrations


def reset_running_calculation_tasks(apps, schema_editor):
    """Update all RUNNING calculation tasks to SCHEDULED."""
    ConcurrentUsageCalculationTask = apps.get_model(
        "api", "ConcurrentUsageCalculationTask"
    )
    for task in ConcurrentUsageCalculationTask.objects.filter(status="RUNNING"):
        task.status = "SCHEDULED"
        task.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_instancedefinition"),
    ]

    operations = [
        migrations.RunPython(reset_running_calculation_tasks),
    ]
