# Generated by Django 3.2.4 on 2021-07-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_auto_20210429_1854"),
    ]

    operations = [
        migrations.RenameField(
            model_name="instancedefinition",
            old_name="memory",
            new_name="memory_mib",
        ),
        migrations.AlterField(
            model_name="instancedefinition",
            name="vcpu",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=32),
        ),
    ]
