# Generated by Django 3.2.5 on 2021-07-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210722_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concurrentusage',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
