# Generated by Django 3.2.6 on 2021-08-27 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_cloudaccount_platform_application_is_paused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudaccount',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cloudaccount',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
