# Generated by Django 3.2.7 on 2021-09-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_auto_20210827_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="awsmachineimage",
            name="product_codes",
            field=models.JSONField(null=True),
        ),
    ]
