# Generated by Django 3.2.10 on 2021-12-15 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_awsmachineimage_usage_operation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="azurecloudaccount",
            name="tenant_id",
        ),
        migrations.AlterField(
            model_name="azurecloudaccount",
            name="subscription_id",
            field=models.UUIDField(unique=True),
        ),
    ]
