# Generated by Django 3.2.12 on 2022-03-18 19:49

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_syntheticdatarequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syntheticdatarequest',
            name='expires_at',
            field=models.DateTimeField(default=api.models.syntheticdatarequest_expires_at_default),
        ),
    ]
