# Generated by Django 3.2.12 on 2022-03-18 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_syntheticdatarequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syntheticdatarequest",
            name="expires_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
