# Generated by Django 3.2.12 on 2022-03-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0056_alter_syntheticdatarequest_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudaccount",
            name="is_synthetic",
            field=models.BooleanField(default=False),
        ),
    ]
