# Generated by Django 3.2.12 on 2022-03-25 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_cloudaccount_is_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="syntheticdatarequest",
            name="run_count_per_instance_min",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
