# Generated by Django 3.2.13 on 2022-06-03 00:47

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_syntheticdatarequest_run_count_per_instance_min'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.TextField(default=api.models.User.user_uuid, max_length=150, unique=True, verbose_name='User Unique Id')),
                ('account_number', models.TextField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Account Number')),
                ('org_id', models.TextField(db_index=True, max_length=150, null=True, unique=True, verbose_name='Org Id')),
                ('is_active', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Joined')),
            ],
        ),
    ]
