# Generated by Django 3.2.12 on 2022-05-06 10:59

from django.db import migrations
from django.contrib.auth.models import User
import environ
import json
import requests


def migrate_account_numbers_to_org_ids(_apps, _schema_editor):
    """Migrate EBS Account Numbers to Org IDs."""

    users_with_no_org_ids = User.objects.filter(last_name="")
    if users_with_no_org_ids:
        user_account_numbers = list(
            users_with_no_org_ids.values_list("username", flat=True)
        )

        env = environ.Env()
        tenant_translator_url = "{}://{}:{}/internal/orgIds".format(
            env("TENANT_TRANSLATOR_SCHEME"),
            env("TENANT_TRANSLATOR_HOST"),
            env("TENANT_TRANSLATOR_PORT"),
        )

        response = requests.post(tenant_translator_url, data=json.dumps(user_account_numbers))
        org_ids = response.json()
        for user_account in users_with_no_org_ids:
            account_number = user_account.username
            if account_number in org_ids:
                org_id = org_ids[account_number]
                user_account.last_name = org_id
                user_account.save()


def reverse_to_account_numbers(_apps, _schema_editor):
    """Reverse to just EBS Account Numbers."""

    users_with_org_ids = User.objects.exclude(last_name="")
    if users_with_org_ids:
        for user_account in users_with_org_ids:
            user_account.last_name = ""
            user_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_syntheticdatarequest_run_count_per_instance_min"),
    ]

    operations = [
        migrations.RunPython(
            migrate_account_numbers_to_org_ids, reverse_code=reverse_to_account_numbers
        )
    ]
