# Generated by Django 3.2.13 on 2022-06-03 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api", "0060_migrate_django_auth_user_to_api_user")]

    operations = [
        migrations.AlterField(
            model_name="cloudaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AlterField(
            model_name="concurrentusage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AlterField(
            model_name="syntheticdatarequest",
            name="user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
        migrations.AlterField(
            model_name="usertasklock",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="api.user"
            ),
        ),
    ]
