# Generated by Django 3.2.12 on 2022-05-06 10:59

from api.models import User
from django.db import migrations
import json
import logging
import requests

from django.conf import settings

logger = logging.getLogger(__name__)


def migrate_account_numbers_to_org_ids(_apps, _schema_editor):
    """Migrate EBS Account Numbers to Org IDs."""

    users_with_no_org_ids = User.objects.filter(org_id=None)
    if users_with_no_org_ids:
        user_account_numbers = list(
            users_with_no_org_ids.values_list("account_number", flat=True)
        )

        tenant_translator_url = "{}://{}:{}/internal/orgIds".format(
            settings.TENANT_TRANSLATOR_SCHEME,
            settings.TENANT_TRANSLATOR_HOST,
            settings.TENANT_TRANSLATOR_PORT,
        )

        logger.info(
            f"Migrating {len(user_account_numbers)} account_numbers to org_id"
        )
        try:
            logger.info(f"Calling tenant translator API {tenant_translator_url}")
            response = requests.post(tenant_translator_url, data=json.dumps(user_account_numbers))
            org_ids = response.json()

            for user_account in users_with_no_org_ids:
                account_number = user_account.account_number
                if account_number in org_ids:
                    org_id = org_ids[account_number]
                    user_account.org_id = org_id
                    user_account.save()
                    logger.info(
                        f"  Migrated user account_number {account_number} "
                        f"to org_id {org_id}"
                    )

        except Exception as e:
            logger.warning(
                f"Failed to migrate account_numbers to org_ids - {e}", exc_info=True
            )


def reverse_to_account_numbers(_apps, _schema_editor):
    """Reverse to just EBS Account Numbers."""

    users_with_org_ids = User.objects.exclude(org_id=None)
    if users_with_org_ids:
        for user_account in users_with_org_ids:
            user_account.org_id = None
            user_account.save()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_migrate_foreign_keys_to_api_user")
    ]

    operations = [
        migrations.RunPython(
            migrate_account_numbers_to_org_ids, reverse_code=reverse_to_account_numbers
        )
    ]
