# Generated by Django 3.2.14 on 2022-08-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20220728_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
    ]
