# Generated by Django 3.2.15 on 2022-10-03 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_user_is_permanent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineimage',
            name='inspection_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
