# Generated by Django 4.1.3 on 2022-11-22 19:21
# This migration removes any remaining celery scheduled jobs related to metering.

from django.db import migrations


def delete_periodic_metering_tasks(apps, schema_editor):
    periodic_metering_tasks = [
        "api.tasks.persist_inspection_cluster_results_task",
        "api.tasks.inspect_pending_images",
        "api.tasks.recalculate_runs_for_all_cloud_accounts",
        "api.tasks.recalculate_concurrent_usage_for_all_users",
        "api.clouds.aws.tasks.repopulate_ec2_instance_mapping",
        "api.clouds.azure.tasks.repopulate_azure_instance_mapping",
        "api.clouds.azure.tasks.update_azure_instance_events",
    ]
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    for metering_task in periodic_metering_tasks:
        PeriodicTask.objects.filter(task=metering_task).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_user_is_permanent"),
    ]

    operations = [
        migrations.RunPython(delete_periodic_metering_tasks),
    ]
