# Generated by Django 3.2.15 on 2022-10-03 20:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_machineimage_inspection_json"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concurrentusage",
            name="_maximum_counts",
            field=models.JSONField(
                db_column="maximum_counts", default=api.models.maximum_counts_default
            ),
        ),
    ]
