# Generated by Django 4.1.5 on 2023-01-25 16:16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_alter_concurrentusage_options_and_more"),
    ]

    # Update only Django's internal model representation to convert the old fields
    # without dropping and recreating table columns. We don't need to alter the database
    # schema because indexes and constraints were dropped in migration 0066.
    state_operations = [
        # Instance.cloud_account to cloud_account_id
        migrations.AlterField(
            model_name="Instance",
            name="cloud_account",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="Instance",
            old_name="cloud_account",
            new_name="cloud_account_id",
        ),
        # Instance.machine_image to machine_image_id
        migrations.AlterField(
            model_name="Instance",
            name="machine_image",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="Instance",
            old_name="machine_image",
            new_name="machine_image_id",
        ),
        # Run.machineimage to machineimage_id
        migrations.AlterField(
            model_name="Run",
            name="machineimage",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="Run",
            old_name="machineimage",
            new_name="machineimage_id",
        ),
        # Run.instance to instance_id
        migrations.AlterField(
            model_name="Run",
            name="instance",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="Run",
            old_name="instance",
            new_name="instance_id",
        ),
        # MachineImageInspectionStart.machineimage to machineimage_id
        migrations.AlterField(
            model_name="MachineImageInspectionStart",
            name="machineimage",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="MachineImageInspectionStart",
            old_name="machineimage",
            new_name="machineimage_id",
        ),
        # ConcurrentUsage.user to user_id
        migrations.AlterField(
            model_name="ConcurrentUsage",
            name="user",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="ConcurrentUsage",
            old_name="user",
            new_name="user_id",
        ),
        # InstanceEvent.instance to instance_id
        migrations.AlterField(
            model_name="InstanceEvent",
            name="instance",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="InstanceEvent",
            old_name="instance",
            new_name="instance_id",
        ),
        # AwsMachineImageCopy.reference_awsmachineimage to reference_awsmachineimage_id
        migrations.AlterField(
            model_name="AwsMachineImageCopy",
            name="reference_awsmachineimage",
            field=models.IntegerField(db_index=False, null=True),
        ),
        migrations.RenameField(
            model_name="AwsMachineImageCopy",
            old_name="reference_awsmachineimage",
            new_name="reference_awsmachineimage_id",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[], state_operations=state_operations
        )
    ]
