# Generated by Django 4.1.3 on 2022-11-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_alter_concurrentusage__maximum_counts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="concurrentusage",
            old_name="_maximum_counts",
            new_name="maximum_counts",
        ),
    ]
