# Generated by Django 4.1.5 on 2023-01-30 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0070_delete_syntheticdatarequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConcurrentUsage",
        ),
    ]
