# Generated by Django 4.1.5 on 2023-01-30 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0071_delete_concurrentusage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Run",
        ),
    ]
