# Generated by Django 4.1.5 on 2023-01-30 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0072_delete_run"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AzureInstance",
        ),
        migrations.DeleteModel(
            name="AzureInstanceEvent",
        ),
        migrations.DeleteModel(
            name="AzureMachineImage",
        ),
    ]
