# Generated by Django 4.1.5 on 2023-01-31 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0073_delete_azureinstance_delete_azureinstanceevent_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AwsInstanceEvent",
        ),
        migrations.DeleteModel(
            name="InstanceEvent",
        ),
    ]
