# Generated by Django 4.1.5 on 2023-01-31 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0074_delete_awsinstanceevent_delete_instanceevent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AwsInstance",
        ),
        migrations.RemoveField(
            model_name="instance",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="InstanceDefinition",
        ),
        migrations.DeleteModel(
            name="Instance",
        ),
    ]
