# Generated by Django 4.1.5 on 2023-01-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0075_delete_awsinstance_remove_instance_content_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="awsmachineimagecopy",
            name="awsmachineimage_ptr",
        ),
        migrations.RemoveField(
            model_name="machineimage",
            name="content_type",
        ),
        migrations.DeleteModel(
            name="MachineImageInspectionStart",
        ),
        migrations.DeleteModel(
            name="AwsMachineImage",
        ),
        migrations.DeleteModel(
            name="AwsMachineImageCopy",
        ),
        migrations.DeleteModel(
            name="MachineImage",
        ),
    ]
