# Generated by Django 4.1.6 on 2023-02-02 17:42

from django.db import migrations


def delete_unused_periodic_tasks(apps, schema_editor):
    periodic_metering_tasks = [
        "api.tasks.check_and_cache_sqs_queues_lengths",
        "api.tasks.delete_expired_synthetic_data",
    ]
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    for metering_task in periodic_metering_tasks:
        PeriodicTask.objects.filter(task=metering_task).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0076_remove_awsmachineimagecopy_awsmachineimage_ptr_and_more"),
    ]

    operations = [
        migrations.RunPython(delete_unused_periodic_tasks),
    ]
