# Generated by Django 4.2.11 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_remove_cloudaccount_is_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscloudaccount",
            name="external_id",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
