# Generated by Django 4.2.11 on 2024-09-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0078_remove_cloudaccount_is_synthetic"),
    ]

    operations = [
        migrations.AddField(
            model_name="awscloudaccount",
            name="external_id",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
