{
 "title": "Cloudigrade",
 "description": "Django metrics dashboard using korfuri/django-prometheus Prometheus metrics exporter",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "kubernetes_namespace",
    "query": "label_values(django_db_new_connections_total, kubernetes_namespace)"
   },
   {
    "name": "app",
    "label": "app",
    "query": "label_values(django_db_new_connections_total{kubernetes_namespace=~\"$kubernetes_namespace\"}, app)"
   }
  ]
 },
 "panels": [
  { "title": "Quick Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Python Version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "sum(python_info{kubernetes_namespace=\"$kubernetes_namespace\",app=~\"^$app$\"}) by (version)",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "2XX Responses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"2.+\",kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "4XX Responses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"4.+\",kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "5XX Responses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{status=~\"5.+\",kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Create Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "listener_processed_events_total{event_type=\"create\",kubernetes_namespace=~\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Update Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "listener_processed_events_total{event_type=\"update\",kubernetes_namespace=~\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Destroy Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "listener_processed_events_total{event_type=\"destroy\",kubernetes_namespace=~\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Unapplied Migrations",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(django_migrations_unapplied_total{kubernetes_namespace=\"$kubernetes_namespace\",app=~\"^$app$\",template=\"cloudigrade\"}) by (template)"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "singlestat",
   "description": "increase(v range-vector) calculates the increase in the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. The increase is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if a counter increases only by integer increments.",
   "gridPos": { "h": 2, "w": 9, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_transport_total{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Processed Events",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 9, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "listener_processed_events_total{event_type=\"total\",kubernetes_namespace=~\"$kubernetes_namespace\"}"
    }
   ]
  },
  {
   "title": "Applied Migrations",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(django_migrations_applied_total{kubernetes_namespace=\"$kubernetes_namespace\",app=~\"^$app$\",template=\"cloudigrade\"}) by (template)"
    }
   ]
  },
  { "title": "API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_requests_total_by_view_transport_method_total{kubernetes_namespace=\"$kubernetes_namespace\",app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home\"}[1m])) by(view, method)",
     "legendFormat": "{{method}} {{view}}"
    }
   ]
  },
  {
   "title": "Responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_before_middlewares_total{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|health_check:health_check_home\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|api.internal.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=50 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|api.internal.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=95 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|api.internal.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=99 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|api.internal.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=99.9 / {{view}}"
    }
   ]
  },
  {
   "title": "Request Latency (Internal)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|v2.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=50 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|v2.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=95 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|v2.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=99 / {{view}}"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(django_http_requests_latency_seconds_by_view_method_bucket{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\",view!~\"prometheus-django-metrics|health_check:health_check_home|v2.+\"}[5m])) by (view, le))",
     "legendFormat": "quantile=99.9 / {{view}}"
    }
   ]
  },
  {
   "title": "Response Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_http_responses_total_by_status_total{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\", view!~\"prometheus-django-metrics|health_check:health_check_home\"}[1m])) by(status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Database Ops",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_db_execute_total{kubernetes_namespace=~\"$kubernetes_namespace\", app=~\"^$app$\"}[1m])) by (vendor)",
     "legendFormat": "{{vendor}}"
    }
   ]
  },
  {
   "title": "CloudAccount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_inserts_total{model=\"CloudAccount\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{model=\"CloudAccount\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(django_model_deletes_total{model=\"CloudAccount\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "MachineImage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_inserts_total{model=\"MachineImage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{model=\"MachineImage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(django_model_deletes_total{model=\"MachineImage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "Instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_inserts_total{model=\"Instance\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{model=\"Instance\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(django_model_deletes_total{model=\"Instance\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "ConcurrentUsage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_inserts_total{model=\"ConcurrentUsage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{model=\"ConcurrentUsage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(django_model_deletes_total{model=\"ConcurrentUsage\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Deletes"
    }
   ]
  },
  {
   "title": "ConcurrentUsageTask",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(django_model_inserts_total{model=\"ConcurrentUsageTask\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Inserts"
    },
    {
     "expr": "sum(irate(django_model_updates_total{model=\"ConcurrentUsageTask\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(irate(django_model_deletes_total{model=\"ConcurrentUsageTask\",kubernetes_namespace=\"$kubernetes_namespace\"}[1m])) by (model)",
     "legendFormat": "Deletes"
    }
   ]
  }
 ]
}