# Generated by Django 2.0.2 on 2018-03-13 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstanceEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('power_on', 'power_on'), ('power_off', 'power_off')], max_length=32)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwsAccount',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Account')),
                ('aws_account_id', models.DecimalField(db_index=True, decimal_places=0, max_digits=12)),
                ('account_arn', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
            bases=('account.account',),
        ),
        migrations.CreateModel(
            name='AwsInstance',
            fields=[
                ('instance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.Instance')),
                ('ec2_instance_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('region', models.CharField(max_length=256)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
            bases=('account.instance',),
        ),
        migrations.CreateModel(
            name='AwsInstanceEvent',
            fields=[
                ('instanceevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.InstanceEvent')),
                ('subnet', models.CharField(max_length=256)),
                ('ec2_ami_id', models.CharField(max_length=256)),
                ('instance_type', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
            bases=('account.instanceevent',),
        ),
        migrations.AddField(
            model_name='instanceevent',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Instance'),
        ),
        migrations.AddField(
            model_name='instance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
    ]
