# Generated by Django 2.0.2 on 2018-02-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_id', models.DecimalField(db_index=True, decimal_places=0, max_digits=12)),
                ('account_arn', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
