# Generated by Django 2.0.2 on 2018-02-19 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_instance_instanceevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceevent',
            name='instance_type',
            field=models.CharField(default='unknown', max_length=64),
            preserve_default=False,
        ),
    ]
