# Generated by Django 2.0.3 on 2018-03-26 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0002_auto_20180319_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_windows', models.BooleanField()),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AwsMachineImage',
            fields=[
                ('machineimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.MachineImage')),
                ('ec2_ami_id', models.CharField(db_index=True, max_length=256, unique=True)),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
            bases=('account.machineimage',),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_account.machineimage_set+', to='contenttypes.ContentType'),
        ),
    ]
