# Generated by Django 2.0.2 on 2018-03-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_instanceevent_instance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instanceevent',
            name='subnet',
            field=models.CharField(max_length=256),
        ),
    ]
