# Generated by Django 2.0.3 on 2018-03-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180326_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsaccount',
            name='aws_account_id',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
