# Generated by Django 2.0.3 on 2018-04-09 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180328_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineimage',
            name='is_encrypted',
            field=models.NullBooleanField(),
        ),
    ]
