# Generated by Django 2.0.5 on 2018-06-01 10:14

from django.db import migrations, models
import django.db.models.deletion


def migrate_is_windows_to_property(apps, schema_editor):
    """Copy old is_windows value to an image tag."""
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # Create image tags
    ImageTag = apps.get_model('account', 'ImageTag')
    image_tag_ct = ContentType.objects.get_for_model(ImageTag)

    windows_tag = ImageTag.objects.create(
        description='windows', polymorphic_ctype=image_tag_ct)
    ImageTag.objects.create(description='rhel', polymorphic_ctype=image_tag_ct)

    # Get current machine images
    MachineImage = apps.get_model('account', 'MachineImage')
    all_images = MachineImage.objects.filter(is_windows=True)

    # Update all windows images
    for image in all_images:
        image.tags.add(windows_tag)
        image.is_windows = None
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('account', '0006_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=32)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                        related_name='polymorphic_account.imagetag_set+', to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='machineimage',
            name='tags',
            field=models.ManyToManyField(to='account.ImageTag', blank=True),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='inspection_json',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='machineimage',
            name='is_windows',
            field=models.NullBooleanField(),
        ), migrations.RunPython(migrate_is_windows_to_property),
        migrations.RemoveField(
            model_name='machineimage',
            name='is_windows',
        ),
    ]
