# Generated by Django 2.0.5 on 2018-06-01 10:14

from django.db import migrations, models
import django.db.models.deletion


def migrate_is_windows_to_property(apps, schema_editor):
    """Copy old is_windows value to an image tag."""

    # Create image tags
    ImageTag = apps.get_model('account', 'ImageTag')
    windows_tag = ImageTag.objects.create(description='windows')
    ImageTag.objects.create(description='rhel')

    # Get current machine images
    MachineImage = apps.get_model('account', 'MachineImage')
    windows_images = MachineImage.objects.filter(is_windows=True)

    # Update all windows images
    for image in windows_images:
        image.tags.add(windows_tag)
        image.is_windows = None
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('account', '0006_account_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False, to='util.BaseModel')),
                ('description', models.CharField(max_length=32)),
            ],
            bases=('util.basemodel',),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='tags',
            field=models.ManyToManyField(to='account.ImageTag', blank=True),
        ),
        migrations.AddField(
            model_name='machineimage',
            name='inspection_json',
            field=models.TextField(null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='machineimage',
            name='is_windows',
            field=models.NullBooleanField(),
        ), migrations.RunPython(migrate_is_windows_to_property),
        migrations.RemoveField(
            model_name='machineimage',
            name='is_windows',
        ),
    ]
