# Generated by Django 2.0.6 on 2018-06-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_add_image_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('preparing', 'Preparing for Inspection'), ('inspecting', 'Being Inspected'), ('inspected', 'Inspected')], default='pending', max_length=10),
        ),
    ]
