# Generated by Django 2.0.6 on 2018-06-28 18:46

from django.db import migrations, models
import django.db.models.deletion


def add_openshift_tag(apps, schema_editor):
    """Copy old is_windows value to an image tag."""

    # Create image tags
    ImageTag = apps.get_model('account', 'ImageTag')
    ImageTag.objects.create(description='openshift')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_awsmachineimagecopy'),
    ]

    operations = [
        migrations.RunPython(add_openshift_tag),
    ]
