# Generated by Django 2.0.6 on 2018-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_openshift_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True),
        ),
    ]
