# Generated by Django 2.0.7 on 2018-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_unique_clount_name_per_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineimage',
            name='account',
        ),
        migrations.AddField(
            model_name='awsmachineimage',
            name='owner_aws_account_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
