# Generated by Django 2.1 on 2018-08-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_awsmachineimage_owner_aws_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineimage',
            name='rhel_detected',
        ),
    ]
