# Generated by Django 2.1 on 2018-08-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_remove_machineimage_rhel_detected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('preparing', 'Preparing for Inspection'), ('inspecting', 'Being Inspected'), ('inspected', 'Inspected'), ('error', 'Error')], default='pending', max_length=10),
        ),
    ]
