# Generated by Django 2.1.2 on 2018-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_awsmachineimage_20181217_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machineimage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('preparing', 'Preparing for Inspection'), ('inspecting', 'Being Inspected'), ('inspected', 'Inspected'), ('error', 'Error'), ('unavailable', 'Unavailable for Inspection')], default='pending', max_length=32),
        ),
    ]
