# Generated by Django 2.1.2 on 2018-11-18 14:12
import logging

from django.db import migrations
from django.db.models import F

logger = logging.getLogger(__name__)

def delete_old_events(apps, schema_editor):
    """
    Delete instance events that we should never have seen because they're older
    than the accounts they belong to.
    """
    AwsInstanceEvent = apps.get_model('account', 'AwsInstanceEvent')
    old_events = AwsInstanceEvent.objects.filter(
        occurred_at__lt=F('instance__account__created_at')
    ).all()
    for old_event in old_events:
        logger.info(
            'deleting {event}: {event_repr}'.format(
                event=str(old_event), event_repr=repr(old_event)
            )
        )
        old_event.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0027_update_machineimage_status'),
    ]

    operations = [
        migrations.RunPython(
            delete_old_events, reverse_code=migrations.RunPython.noop
        ),
    ]
