# Generated by Django 2.1.2 on 2019-01-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_delete_old_events'),
        ('account', '0028_add-region-to-aws-images'),
    ]

    operations = [
    ]
