# Generated by Django 2.1.2 on 2019-01-23 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_merge_20190122_1627'),
        ('account', '0028_instance_machineimage'),
    ]

    operations = [
    ]
