# Generated by Django 2.1.2 on 2019-01-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0030_instance_machineimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsaccount',
            name='aws_account_id',
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=12),
        ),
    ]
