# Generated by Django 2.1.2 on 2019-02-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_alter_awsaccount_aws_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('instance_type', models.CharField(blank=True, max_length=64, null=True)),
                ('memory', models.FloatField(blank=True, default=0, null=True)),
                ('vcpu', models.IntegerField(blank=True, default=0, null=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Instance')),
                ('machineimage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.MachineImage')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
