# Generated by Django 2.1.7 on 2019-03-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0032_update_machineimage_status'),
        ('account', '0032_add_run_model'),
    ]

    operations = [
    ]
