# Generated by Django 2.1.5 on 2019-03-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_merge_20190304_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsmachineimage',
            name='aws_marketplace_image',
            field=models.BooleanField(default=False),
        ),
    ]
