# Generated by Django 2.1.2 on 2019-03-04 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_add_aws_marketplace_image_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineImageInspectionStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('machineimage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.MachineImage')),
            ],
            options={
                'ordering': ('created_at',),
                'abstract': False,
            },
        ),
    ]
