# Generated by Django 2.1.5 on 2019-04-10 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0035_machineimageinspectionstart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineimageinspectionstart',
            name='occurred_at',
        ),
    ]
