---
# Create Block
- block:
  - name: create / generate image tag
    shell: echo "`date +'%Y%m%d%H%M%S'`"
    args:
      chdir: "{{ cloudigrade_deployment_repo }}"
    register: new_image_tag

  - debug: var=new_image_tag.stdout

  - name: create / build cloudigrade
    shell: docker build . --tag quay.io/{{ quay_user }}/cloudigrade:{{ new_image_tag.stdout }}
    args:
      chdir: "{{ cloudigrade_deployment_repo }}"

  - name: create / build postigrade
    shell: docker build . --tag quay.io/{{ quay_user }}/postigrade:{{ new_image_tag.stdout }}
    args:
      chdir: "{{ postigrade_deployment_repo }}"

  - name: create / push cloudigrade
    shell: docker push quay.io/{{ quay_user }}/cloudigrade:{{ new_image_tag.stdout }}
    args:
      chdir: "{{ cloudigrade_deployment_repo }}"

  - name: create / push postigrade
    shell: docker push quay.io/{{ quay_user }}/postigrade:{{ new_image_tag.stdout }}
    args:
      chdir: "{{ postigrade_deployment_repo }}"

  - name: create / oc create pull secret
    shell: oc apply -f {{ pull_secret_path }} --namespace {{ namespace }}

  - name: create / patch env-{{namespace}}
    shell: oc patch ClowdEnvironment/env-{{ namespace }} --type=merge -p '{"spec":{"providers":{"pullSecrets":[{"name":"quay-cloudservices-pull","namespace":"ephemeral-base"},{"name":"{{ quay_user }}-pull-secret","namespace":"{{ namespace }}"}]}}}'

  when: push_local_state == "present"
